/**
 * Weather simulation presets for major agricultural clusters in India
 */
export const WEATHER_REGIONS = [
  { id: 'nashik', name: 'Nashik, Maharashtra', lat: 19.9975, lon: 73.7898 },
  { id: 'pune', name: 'Pune, Maharashtra', lat: 18.5204, lon: 73.8567 },
  { id: 'indore', name: 'Indore, Madhya Pradesh', lat: 22.7196, lon: 75.8577 },
  { id: 'karnal', name: 'Karnal, Haryana', lat: 29.6857, lon: 76.9905 },
  { id: 'ludhiana', name: 'Ludhiana, Punjab', lat: 30.9010, lon: 75.8573 },
  { id: 'warangal', name: 'Warangal, Telangana', lat: 17.9689, lon: 79.5941 },
];

export const MOCK_WEATHER_DATA_BY_REGION = {
  nashik: {
    location: 'Nashik, Maharashtra',
    temperature: 28,
    condition: 'Partly Cloudy',
    conditionKey: 'partly-cloudy',
    humidity: 62,
    windSpeed: 12,
    rainProbability: 20,
    advisory: 'Favorable conditions for vegetable spray and field aeration.',
    forecast: [
      { day: 'Today', temp: 28, minTemp: 21, condition: 'Partly Cloudy', icon: 'partly-cloudy', rain: 20 },
      { day: 'Tue', temp: 29, minTemp: 22, condition: 'Sunny', icon: 'sunny', rain: 10 },
      { day: 'Wed', temp: 27, minTemp: 20, condition: 'Scattered Showers', icon: 'rain', rain: 45 },
      { day: 'Thu', temp: 26, minTemp: 19, condition: 'Cloudy', icon: 'cloudy', rain: 30 },
      { day: 'Fri', temp: 28, minTemp: 21, condition: 'Clear Sky', icon: 'sunny', rain: 5 },
    ],
  },
  pune: {
    location: 'Pune, Maharashtra',
    temperature: 29,
    condition: 'Clear Sky',
    conditionKey: 'sunny',
    humidity: 55,
    windSpeed: 10,
    rainProbability: 10,
    advisory: 'Optimal window for harvesting grains and open sun drying.',
    forecast: [
      { day: 'Today', temp: 29, minTemp: 22, condition: 'Clear Sky', icon: 'sunny', rain: 10 },
      { day: 'Tue', temp: 30, minTemp: 22, condition: 'Sunny', icon: 'sunny', rain: 5 },
      { day: 'Wed', temp: 28, minTemp: 21, condition: 'Partly Cloudy', icon: 'partly-cloudy', rain: 25 },
      { day: 'Thu', temp: 27, minTemp: 20, condition: 'Light Rain', icon: 'rain', rain: 40 },
      { day: 'Fri', temp: 28, minTemp: 20, condition: 'Partly Cloudy', icon: 'partly-cloudy', rain: 15 },
    ],
  },
  indore: {
    location: 'Indore, Madhya Pradesh',
    temperature: 31,
    condition: 'Sunny',
    conditionKey: 'sunny',
    humidity: 48,
    windSpeed: 14,
    rainProbability: 5,
    advisory: 'Low moisture levels. Early morning irrigation recommended for pulses.',
    forecast: [
      { day: 'Today', temp: 31, minTemp: 23, condition: 'Sunny', icon: 'sunny', rain: 5 },
      { day: 'Tue', temp: 32, minTemp: 24, condition: 'Hot & Clear', icon: 'sunny', rain: 0 },
      { day: 'Wed', temp: 30, minTemp: 23, condition: 'Partly Cloudy', icon: 'partly-cloudy', rain: 15 },
      { day: 'Thu', temp: 29, minTemp: 22, condition: 'Scattered Showers', icon: 'rain', rain: 35 },
      { day: 'Fri', temp: 30, minTemp: 22, condition: 'Sunny', icon: 'sunny', rain: 10 },
    ],
  },
  karnal: {
    location: 'Karnal, Haryana',
    temperature: 26,
    condition: 'Mild Breeze',
    conditionKey: 'windy',
    humidity: 68,
    windSpeed: 16,
    rainProbability: 15,
    advisory: 'Ideal conditions for wheat field inspection and nutrient check.',
    forecast: [
      { day: 'Today', temp: 26, minTemp: 18, condition: 'Mild Breeze', icon: 'partly-cloudy', rain: 15 },
      { day: 'Tue', temp: 27, minTemp: 19, condition: 'Sunny', icon: 'sunny', rain: 5 },
      { day: 'Wed', temp: 25, minTemp: 17, condition: 'Light Rain', icon: 'rain', rain: 50 },
      { day: 'Thu', temp: 24, minTemp: 16, condition: 'Overcast', icon: 'cloudy', rain: 30 },
      { day: 'Fri', temp: 26, minTemp: 18, condition: 'Clear Sky', icon: 'sunny', rain: 10 },
    ],
  },
  ludhiana: {
    location: 'Ludhiana, Punjab',
    temperature: 27,
    condition: 'Clear Sky',
    conditionKey: 'sunny',
    humidity: 60,
    windSpeed: 11,
    rainProbability: 10,
    advisory: 'Stable weather ahead. Good window for crop protection spraying.',
    forecast: [
      { day: 'Today', temp: 27, minTemp: 19, condition: 'Clear Sky', icon: 'sunny', rain: 10 },
      { day: 'Tue', temp: 28, minTemp: 20, condition: 'Sunny', icon: 'sunny', rain: 5 },
      { day: 'Wed', temp: 26, minTemp: 18, condition: 'Cloudy', icon: 'cloudy', rain: 20 },
      { day: 'Thu', temp: 25, minTemp: 17, condition: 'Showers', icon: 'rain', rain: 45 },
      { day: 'Fri', temp: 27, minTemp: 18, condition: 'Partly Cloudy', icon: 'partly-cloudy', rain: 15 },
    ],
  },
  warangal: {
    location: 'Warangal, Telangana',
    temperature: 32,
    condition: 'Partly Cloudy',
    conditionKey: 'partly-cloudy',
    humidity: 58,
    windSpeed: 13,
    rainProbability: 25,
    advisory: 'Warm humid conditions. Monitor chilli and cotton for pest activity.',
    forecast: [
      { day: 'Today', temp: 32, minTemp: 24, condition: 'Partly Cloudy', icon: 'partly-cloudy', rain: 25 },
      { day: 'Tue', temp: 31, minTemp: 24, condition: 'Thunderstorm Chance', icon: 'rain', rain: 60 },
      { day: 'Wed', temp: 29, minTemp: 23, condition: 'Rain', icon: 'rain', rain: 70 },
      { day: 'Thu', temp: 30, minTemp: 23, condition: 'Cloudy', icon: 'cloudy', rain: 35 },
      { day: 'Fri', temp: 32, minTemp: 24, condition: 'Sunny', icon: 'sunny', rain: 15 },
    ],
  },
};
