/**
 * Realistic Indian agricultural market data (Mandi prices in INR per quintal)
 * Clearly separated for development and fallback simulation.
 */
export const MOCK_CROP_PRICES = [
  {
    id: 'crop-wheat',
    name: 'Wheat',
    hindiName: 'गेहूं (Sharbati)',
    price: 2450,
    unit: 'quintal',
    changeAmount: 43.5,
    changePercent: 1.8,
    isPositive: true,
    mandi: 'Indore Mandi, MP',
    variety: 'Grade A',
    sparkline: [2380, 2395, 2410, 2400, 2435, 2450],
    iconType: 'wheat',
  },
  {
    id: 'crop-rice',
    name: 'Rice (Basmati)',
    hindiName: 'चावल (Basmati 1121)',
    price: 3820,
    unit: 'quintal',
    changeAmount: -35.0,
    changePercent: -0.9,
    isPositive: false,
    mandi: 'Karnal Mandi, HR',
    variety: 'Milled Standard',
    sparkline: [3900, 3880, 3865, 3850, 3830, 3820],
    iconType: 'rice',
  },
  {
    id: 'crop-maize',
    name: 'Maize',
    hindiName: 'मक्का (Yellow Corn)',
    price: 2180,
    unit: 'quintal',
    changeAmount: 52.0,
    changePercent: 2.4,
    isPositive: true,
    mandi: 'Chhindwara Mandi, MP',
    variety: 'Feed Grade',
    sparkline: [2090, 2110, 2130, 2145, 2160, 2180],
    iconType: 'corn',
  },
  {
    id: 'crop-onion',
    name: 'Onion',
    hindiName: 'प्याज (Nashik Red)',
    price: 2200,
    unit: 'quintal',
    changeAmount: 88.0,
    changePercent: 4.2,
    isPositive: true,
    mandi: 'Lasalgaon Mandi, MH',
    variety: 'Medium Red',
    sparkline: [2050, 2080, 2110, 2140, 2180, 2200],
    iconType: 'onion',
  },
  {
    id: 'crop-tomato',
    name: 'Tomato',
    hindiName: 'टमाटर (Hybrid)',
    price: 1850,
    unit: 'quintal',
    changeAmount: -40.0,
    changePercent: -2.1,
    isPositive: false,
    mandi: 'Kolar Mandi, KA',
    variety: 'Grade 1 Red',
    sparkline: [1940, 1920, 1890, 1910, 1870, 1850],
    iconType: 'tomato',
  },
  {
    id: 'crop-soybean',
    name: 'Soybean',
    hindiName: 'सोयाबीन (Yellow)',
    price: 4620,
    unit: 'quintal',
    changeAmount: 65.0,
    changePercent: 1.4,
    isPositive: true,
    mandi: 'Kota Mandi, RJ',
    variety: 'Standard Dry',
    sparkline: [4500, 4530, 4550, 4580, 4600, 4620],
    iconType: 'soybean',
  },
];

export const MARKET_TREND_SUMMARY = {
  lastUpdated: 'Today at 09:30 AM IST',
  activeMandis: 148,
  overallMarketSentiment: 'Bullish (+1.6% average index)',
};
